<?php
// database/seeders/LembagaSeeder.php

namespace Database\Seeders;

use App\Models\Lembaga;
use App\Models\Yayasan;
use Illuminate\Database\Seeder;

class LembagaSeeder extends Seeder
{
    public function run(): void
    {
        $yayasan = Yayasan::firstOrFail();

        Lembaga::firstOrCreate(
            ['npsn' => '20223311'],
            [
                'yayasan_id' => $yayasan->id,
                'nss' => '102026001011',
                'kode_lembaga' => 'KBITPTR',
                'nama' => 'KBIT PINTERA',
                'bentuk_pendidikan' => 'KB',
                'status_sekolah' => 'swasta',
                'status_kepemilikan' => 'Yayasan',
                'naungan' => 'kemendikdasmen',
                'sk_pendirian_nomor' => '421.1/SK.011/Disdik/2012',
                'sk_pendirian_tanggal' => '2012-05-10',
                'sk_izin_operasional_nomor' => '421.1/IOP.011/Disdik/2012',
                'sk_izin_operasional_tanggal' => '2012-06-15',
                'akreditasi' => 'A',
                'sk_akreditasi_nomor' => '011/BAN-PAUD/SK/2021',
                'tanggal_sk_akreditasi' => '2021-10-15',
                'nama_kepala_sekolah' => 'Aisyah, S.Psi.',
                'nama_bendahara_bosp' => 'Halimah, S.E.',
                'alamat_jalan' => 'Jl. Panglima Sudirman No. 88A',
                'rt' => '001',
                'rw' => '003',
                'desa_kelurahan' => 'Sidomulyo',
                'kecamatan' => 'Kraksaan',
                'kabupaten_kota' => 'Kabupaten Probolinggo',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '67282',
                'lintang' => '-7.7550000',
                'bujur' => '113.4150000',
                'telepon' => '0335-771231',
                'email' => 'kbit@pintera.sch.id',
                'website' => 'https://kbit.pintera.sch.id',
                'nama_bank' => 'Bank BSI',
                'cabang_kcp_unit' => 'KCP Kraksaan',
                'rekening_atas_nama' => 'KBIT PINTERA',
                'nomor_rekening' => '7123456011',
                'mbs' => true,
                'nama_wajib_pajak' => 'KBIT PINTERA',
                'npwp' => '02.345.671.1-012.000',
                'status_aktif' => true,
            ]
        );

        Lembaga::firstOrCreate(
            ['npsn' => '20223322'],
            [
                'yayasan_id' => $yayasan->id,
                'nss' => '102026001022',
                'kode_lembaga' => 'TKITPTR',
                'nama' => 'TKIT PINTERA',
                'bentuk_pendidikan' => 'TK',
                'status_sekolah' => 'swasta',
                'status_kepemilikan' => 'Yayasan',
                'naungan' => 'kemendikdasmen',
                'sk_pendirian_nomor' => '421.1/SK.022/Disdik/2012',
                'sk_pendirian_tanggal' => '2012-05-10',
                'sk_izin_operasional_nomor' => '421.1/IOP.022/Disdik/2012',
                'sk_izin_operasional_tanggal' => '2012-06-15',
                'akreditasi' => 'A',
                'sk_akreditasi_nomor' => '022/BAN-PAUD/SK/2021',
                'tanggal_sk_akreditasi' => '2021-10-15',
                'nama_kepala_sekolah' => 'Maryam, S.Pd.I.',
                'nama_bendahara_bosp' => 'Khadijah, S.E.',
                'alamat_jalan' => 'Jl. Panglima Sudirman No. 88B',
                'rt' => '001',
                'rw' => '003',
                'desa_kelurahan' => 'Sidomulyo',
                'kecamatan' => 'Kraksaan',
                'kabupaten_kota' => 'Kabupaten Probolinggo',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '67282',
                'lintang' => '-7.7551000',
                'bujur' => '113.4151000',
                'telepon' => '0335-771232',
                'email' => 'tkit@pintera.sch.id',
                'website' => 'https://tkit.pintera.sch.id',
                'nama_bank' => 'Bank BSI',
                'cabang_kcp_unit' => 'KCP Kraksaan',
                'rekening_atas_nama' => 'TKIT PINTERA',
                'nomor_rekening' => '7123456022',
                'mbs' => true,
                'nama_wajib_pajak' => 'TKIT PINTERA',
                'npwp' => '02.345.672.2-012.000',
                'status_aktif' => true,
            ]
        );

        Lembaga::firstOrCreate(
            ['npsn' => '20223333'],
            [
                'yayasan_id' => $yayasan->id,
                'nss' => '102026001033',
                'kode_lembaga' => 'SDITPTR',
                'nama' => 'SDIT PINTERA',
                'bentuk_pendidikan' => 'SD',
                'status_sekolah' => 'swasta',
                'status_kepemilikan' => 'Yayasan',
                'naungan' => 'kemendikdasmen',
                'sk_pendirian_nomor' => '421.2/SK.033/Disdik/2010',
                'sk_pendirian_tanggal' => '2010-06-01',
                'sk_izin_operasional_nomor' => '421.2/IOP.033/Disdik/2010',
                'sk_izin_operasional_tanggal' => '2010-07-15',
                'akreditasi' => 'A',
                'sk_akreditasi_nomor' => '033/BAN-SM/SK/2022',
                'tanggal_sk_akreditasi' => '2022-11-10',
                'nama_kepala_sekolah' => 'Abdullah, M.Pd.',
                'nama_bendahara_bosp' => 'Hasan, S.E.',
                'alamat_jalan' => 'Jl. Panglima Sudirman No. 88C',
                'rt' => '001',
                'rw' => '003',
                'desa_kelurahan' => 'Sidomulyo',
                'kecamatan' => 'Kraksaan',
                'kabupaten_kota' => 'Kabupaten Probolinggo',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '67282',
                'lintang' => '-7.7552000',
                'bujur' => '113.4152000',
                'telepon' => '0335-771233',
                'email' => 'sdit@pintera.sch.id',
                'website' => 'https://sdit.pintera.sch.id',
                'nama_bank' => 'Bank BSI',
                'cabang_kcp_unit' => 'KCP Kraksaan',
                'rekening_atas_nama' => 'SDIT PINTERA',
                'nomor_rekening' => '7123456033',
                'mbs' => true,
                'nama_wajib_pajak' => 'SDIT PINTERA',
                'npwp' => '02.345.673.3-012.000',
                'status_aktif' => true,
            ]
        );

        Lembaga::firstOrCreate(
            ['npsn' => '20223344'],
            [
                'yayasan_id' => $yayasan->id,
                'nss' => '202026001044',
                'kode_lembaga' => 'SMPITPTR',
                'nama' => 'SMPIT PINTERA',
                'bentuk_pendidikan' => 'SMP',
                'status_sekolah' => 'swasta',
                'status_kepemilikan' => 'Yayasan',
                'naungan' => 'kemendikdasmen',
                'sk_pendirian_nomor' => '421.3/SK.044/Disdik/2008',
                'sk_pendirian_tanggal' => '2008-06-01',
                'sk_izin_operasional_nomor' => '421.3/IOP.044/Disdik/2008',
                'sk_izin_operasional_tanggal' => '2008-07-15',
                'akreditasi' => 'A',
                'sk_akreditasi_nomor' => '044/BAN-SM/SK/2022',
                'tanggal_sk_akreditasi' => '2022-11-10',
                'nama_kepala_sekolah' => 'Bambang Suryadi, M.Pd.',
                'nama_bendahara_bosp' => 'Fajar Ramadhan, S.E.',
                'alamat_jalan' => 'Jl. Panglima Sudirman No. 88D',
                'rt' => '001',
                'rw' => '003',
                'desa_kelurahan' => 'Sidomulyo',
                'kecamatan' => 'Kraksaan',
                'kabupaten_kota' => 'Kabupaten Probolinggo',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '67282',
                'lintang' => '-7.7553000',
                'bujur' => '113.4153000',
                'telepon' => '0335-771234',
                'email' => 'smpit@pintera.sch.id',
                'website' => 'https://smpit.pintera.sch.id',
                'nama_bank' => 'Bank BSI',
                'cabang_kcp_unit' => 'KCP Kraksaan',
                'rekening_atas_nama' => 'SMPIT PINTERA',
                'nomor_rekening' => '7123456044',
                'mbs' => true,
                'nama_wajib_pajak' => 'SMPIT PINTERA',
                'npwp' => '02.345.674.4-012.000',
                'status_aktif' => true,
            ]
        );
    }
}
