<?php
// tests/Feature/Admin/JenisTagihanMonitoringTest.php

use App\Models\JenisTagihan;
use App\Models\Lembaga;
use App\Models\Siswa;
use App\Models\Tagihan;
use App\Models\User;
use App\Models\Yayasan;
use Database\Seeders\RolePermissionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

beforeEach(function () {
    (new RolePermissionSeeder)->run();
});

it('denies access to monitoring page without jenis-tagihan.view permission', function () {
    $yayasan = Yayasan::factory()->create();
    $lembaga = Lembaga::factory()->create(['yayasan_id' => $yayasan->id]);
    $user = User::factory()->create(['lembaga_id' => $lembaga->id]);
    
    $jenisTagihan = JenisTagihan::factory()->create(['lembaga_id' => $lembaga->id]);

    $this->actingAs($user)
        ->get(route('admin.jenis-tagihan.monitoring.index', $jenisTagihan))
        ->assertForbidden();
});

it('enforces tenant scope on monitoring page', function () {
    $yayasan = Yayasan::factory()->create();
    $lembaga1 = Lembaga::factory()->create(['yayasan_id' => $yayasan->id]);
    $lembaga2 = Lembaga::factory()->create(['yayasan_id' => $yayasan->id]);
    
    $user1 = User::factory()->create(['lembaga_id' => $lembaga1->id]);
    $user1->assignRole('admin_keuangan');

    $jenisTagihanLembaga2 = JenisTagihan::factory()->create(['lembaga_id' => $lembaga2->id]);

    $this->actingAs($user1)
        ->get(route('admin.jenis-tagihan.monitoring.index', $jenisTagihanLembaga2))
        ->assertNotFound(); // Implicit route model binding fails due to TenantScope
});

it('allows access to monitoring page with proper permission and tenant', function () {
    $yayasan = Yayasan::factory()->create();
    $lembaga = Lembaga::factory()->create(['yayasan_id' => $yayasan->id]);
    $user = User::factory()->create(['lembaga_id' => $lembaga->id]);
    $user->assignRole('admin_keuangan');
    
    $jenisTagihan = JenisTagihan::factory()->create(['lembaga_id' => $lembaga->id]);

    $this->actingAs($user)
        ->get(route('admin.jenis-tagihan.monitoring.index', $jenisTagihan))
        ->assertOk();
});

it('calculates ringkasan metrics correctly', function () {
    $yayasan = Yayasan::factory()->create();
    $lembaga = Lembaga::factory()->create(['yayasan_id' => $yayasan->id]);
    $user = User::factory()->create(['lembaga_id' => $lembaga->id]);
    $user->assignRole('admin_keuangan');
    
    $jenisTagihan = JenisTagihan::factory()->create(['lembaga_id' => $lembaga->id]);

    $siswa1 = Siswa::factory()->create(['lembaga_id' => $lembaga->id]);
    $siswa2 = Siswa::factory()->create(['lembaga_id' => $lembaga->id]);

    // Clear tagihan that were automatically generated by Siswa creation event
    Tagihan::query()->delete();

    // Lunas
    Tagihan::factory()->create([
        'jenis_tagihan_id' => $jenisTagihan->id,
        'tagihable_type' => Siswa::class,
        'tagihable_id' => $siswa1->id,
        'status' => 'lunas',
        'net_amount' => 100000,
        'paid_amount' => 100000,
    ]);

    // Sebagian
    Tagihan::factory()->create([
        'jenis_tagihan_id' => $jenisTagihan->id,
        'tagihable_type' => Siswa::class,
        'tagihable_id' => $siswa1->id,
        'status' => 'sebagian',
        'net_amount' => 150000,
        'paid_amount' => 50000,
    ]);

    // Belum bayar
    Tagihan::factory()->create([
        'jenis_tagihan_id' => $jenisTagihan->id,
        'tagihable_type' => Siswa::class,
        'tagihable_id' => $siswa2->id,
        'status' => 'belum_bayar',
        'net_amount' => 120000,
        'paid_amount' => 0,
    ]);

    // Dibatalkan (should not count for total_tertagih and total_penerima)
    Tagihan::factory()->create([
        'jenis_tagihan_id' => $jenisTagihan->id,
        'tagihable_type' => Siswa::class,
        'tagihable_id' => $siswa2->id,
        'status' => 'dibatalkan',
        'net_amount' => 200000,
        'paid_amount' => 0,
    ]);

    $response = $this->actingAs($user)
        ->get(route('admin.jenis-tagihan.monitoring.index', $jenisTagihan));

    $response->assertOk();
    $response->assertViewHas('ringkasan');
    
    $ringkasan = $response->viewData('ringkasan');
    // total_penerima includes ALL tagihan (4 in total)
    expect($ringkasan['total_penerima'])->toBe(4);
    expect($ringkasan['lunas'])->toBe(1);
    expect($ringkasan['sebagian'])->toBe(1);
    expect($ringkasan['belum_bayar'])->toBe(1);
    expect($ringkasan['dibatalkan'])->toBe(1);
    expect($ringkasan['total_tertagih'])->toBe(370000.0); // 100k + 150k + 120k
    expect($ringkasan['total_masuk'])->toBe(150000.0); // 100k + 50k
});

it('lists daftar penerima correctly with pagination', function () {
    $yayasan = Yayasan::factory()->create();
    $lembaga = Lembaga::factory()->create(['yayasan_id' => $yayasan->id]);
    $user = User::factory()->create(['lembaga_id' => $lembaga->id]);
    $user->assignRole('admin_keuangan');
    
    $jenisTagihan = JenisTagihan::factory()->create(['lembaga_id' => $lembaga->id]);

    $siswa = Siswa::factory()->create(['lembaga_id' => $lembaga->id]);
    
    Tagihan::query()->delete();

    Tagihan::factory()->create([
        'jenis_tagihan_id' => $jenisTagihan->id,
        'tagihable_type' => Siswa::class,
        'tagihable_id' => $siswa->id,
        'status' => 'belum_bayar',
    ]);

    $response = $this->actingAs($user)
        ->get(route('admin.jenis-tagihan.monitoring.index', $jenisTagihan));

    $response->assertOk();
    $response->assertViewHas('tagihanPenerima');
    
    $tagihanPenerima = $response->viewData('tagihanPenerima');
    expect($tagihanPenerima->count())->toBe(1);
    expect($tagihanPenerima->first()->tagihable->id)->toBe($siswa->id);
});
