import './bootstrap';

import Alpine from 'alpinejs';
import anchor from '@alpinejs/anchor';
import flatpickr from 'flatpickr';
import { Indonesian } from 'flatpickr/dist/l10n/id.js';
import { registerToastStore } from './toast-store';
import { registerConfirmDialogStore } from './confirm-dialog-store';
import { registerKelengkapanStore } from './kelengkapan-store';
import { registerFilePreviewStore } from './file-preview';
import { rolesTable } from './roles-table';
import { roleForm } from './role-form';
import { dataDiriForm } from './data-diri-form';
import { formulirTambahanForm } from './formulir-tambahan-form';
import { jadwalPelajaranFilter } from './jadwal-pelajaran-filter';
import { jadwalPelajaranCreateForm } from './jadwal-pelajaran-create';
import { komponenPenilaianFilter } from './komponen-penilaian-filter';
import { komponenPenilaianEditForm } from './komponen-penilaian-edit';
import { komponenPenilaianCreateForm } from './komponen-penilaian-create';
import { raporFilter } from './rapor-filter';
import { otpInput } from './otp-input';
import { pendaftaranTable } from './pendaftaran-table';
import { pendaftaranDetail } from './pendaftaran-detail';
import { nilaiMassal } from './nilai-massal';
import { tagihanTable } from './tagihan-table';
import { pembayaranTable } from './pembayaran-table';
import { trenPendaftaranChart, donutTagihanChart, perLembagaBarChart } from './dashboard-charts';
import { dokumenSyaratList } from './dokumen-syarat-list';
import { formulirFieldList } from './formulir-field-list';
import { seleksiList } from './seleksi-list';
import { jenisTesTable } from './jenis-tes-table';
import { jenisTagihanTable } from './jenis-tagihan-table';
import { kalenderAkademikTable } from './pengaturan-akademik';
import { passwordStrength } from './password-strength';
import { mataPelajaranFilter } from './mata-pelajaran-filter';
import { dataTableFilter } from './data-table-filter';
import { mataPelajaranForm } from './mata-pelajaran-form';
import { orangTuaCari } from './orang-tua-cari';
import { karyawanForm } from './karyawan-form';
import { tomSelectSiswa } from './tom-select-siswa';
import { triaseForm } from './triase-form';

window.Alpine = Alpine;
window.flatpickr = flatpickr;
flatpickr.localize(Indonesian);

Alpine.plugin(anchor);

registerToastStore(Alpine);
registerConfirmDialogStore(Alpine);
registerKelengkapanStore(Alpine);
registerFilePreviewStore(Alpine);
Alpine.data('rolesTable', rolesTable);
Alpine.data('roleForm', roleForm);
Alpine.data('dataDiriForm', dataDiriForm);
Alpine.data('formulirTambahanForm', formulirTambahanForm);
Alpine.data('jadwalPelajaranFilter', jadwalPelajaranFilter);
Alpine.data('jadwalPelajaranCreateForm', jadwalPelajaranCreateForm);
Alpine.data('komponenPenilaianFilter', komponenPenilaianFilter);
Alpine.data('komponenPenilaianEditForm', komponenPenilaianEditForm);
Alpine.data('komponenPenilaianCreateForm', komponenPenilaianCreateForm);
Alpine.data('raporFilter', raporFilter);
Alpine.data('otpInput', otpInput);
Alpine.data('pendaftaranTable', pendaftaranTable);
Alpine.data('pendaftaranDetail', pendaftaranDetail);
Alpine.data('nilaiMassal', nilaiMassal);
Alpine.data('tagihanTable', tagihanTable);
Alpine.data('pembayaranTable', pembayaranTable);
Alpine.data('trenPendaftaranChart', trenPendaftaranChart);
Alpine.data('donutTagihanChart', donutTagihanChart);
Alpine.data('perLembagaBarChart', perLembagaBarChart);
Alpine.data('dokumenSyaratList', dokumenSyaratList);
Alpine.data('formulirFieldList', formulirFieldList);
Alpine.data('seleksiList', seleksiList);
Alpine.data('jenisTesTable', jenisTesTable);
Alpine.data('jenisTagihanTable', jenisTagihanTable);
Alpine.data('kalenderAkademikTable', kalenderAkademikTable);
Alpine.data('passwordStrength', passwordStrength);
Alpine.data('mataPelajaranFilter', mataPelajaranFilter);
Alpine.data('dataTableFilter', dataTableFilter);
Alpine.data('mataPelajaranForm', mataPelajaranForm);
Alpine.data('orangTuaCari', orangTuaCari);
Alpine.data('karyawanForm', karyawanForm);
Alpine.data('tomSelectSiswa', tomSelectSiswa);
Alpine.data('triaseForm', triaseForm);

Alpine.start();
